server:
  port: 6001

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/db2024?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/db2024?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: henry
    password: Henrylee1232.
  redis:
    database: 0
    host: redis
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.henry.docker.db.entity


